# Generated by Django 6.0.2 on 2026-02-05 13:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AlterModelOptions(
            name='favori',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.AlterModelOptions(
            name='imagevoiture',
            options={'ordering': ['ordre'], 'verbose_name': 'Image de voiture', 'verbose_name_plural': 'Images de voitures'},
        ),
        migrations.AlterModelOptions(
            name='marque',
            options={'ordering': ['nom'], 'verbose_name': 'Marque', 'verbose_name_plural': 'Marques'},
        ),
        migrations.AlterModelOptions(
            name='modele',
            options={'ordering': ['marque', 'nom'], 'verbose_name': 'Modèle', 'verbose_name_plural': 'Modèles'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_transaction'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='voiture',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Voiture', 'verbose_name_plural': 'Voitures'},
        ),
        migrations.AddField(
            model_name='imagevoiture',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marque',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modele',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='vue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modele',
            name='consommation',
            field=models.FloatField(default=6.0, help_text='Consommation en L/100km'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='puissance',
            field=models.PositiveIntegerField(default=100, help_text='Puissance en chevaux'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='transmission',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique'), ('semi-auto', 'Semi-automatique')], default='manuelle', max_length=20),
        ),
        migrations.AlterField(
            model_name='modele',
            name='type_carburant',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique'), ('gpl', 'GPL')], default='essence', max_length=20),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='annee',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='couleur',
            field=models.CharField(choices=[('blanc', 'Blanc'), ('noir', 'Noir'), ('gris', 'Gris'), ('rouge', 'Rouge'), ('bleu', 'Bleu'), ('vert', 'Vert'), ('jaune', 'Jaune'), ('argent', 'Argent'), ('orange', 'Orange'), ('violet', 'Violet'), ('marron', 'Marron'), ('beige', 'Beige')], max_length=20),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='image_principale',
            field=models.ImageField(blank=True, default='voitures/default.jpg', upload_to='voitures/'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
